# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2018-02-18 14:42+AKST\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"


#: ../cog_manager.py:308
msgid ""
"Install Path: {}\n"
"\n"
msgstr ""

#: ../cog_manager.py:324
msgid "That path does not exist or does not point to a valid directory."
msgstr ""

#: ../cog_manager.py:333
msgid "Path successfully added."
msgstr ""

#: ../cog_manager.py:346
msgid "That is an invalid path number."
msgstr ""

#: ../cog_manager.py:350
msgid "Path successfully removed."
msgstr ""

#: ../cog_manager.py:366
msgid "Invalid 'from' index."
msgstr ""

#: ../cog_manager.py:372
msgid "Invalid 'to' index."
msgstr ""

#: ../cog_manager.py:376
msgid "Paths reordered."
msgstr ""

#: ../cog_manager.py:394
msgid "That path does not exist."
msgstr ""

#: ../cog_manager.py:398
msgid "The bot will install new cogs to the `{}` directory."
msgstr ""

#: ../core_commands.py:224 ../core_commands.py:258
msgid "No module by that name was found in any cog path."
msgstr ""

#: ../core_commands.py:232
msgid "Failed to load package. Check your console or logs for details."
msgstr ""

#: ../core_commands.py:236 ../core_commands.py:245 ../core_commands.py:270
#: ../core_commands.py:359 ../core_commands.py:447 ../core_commands.py:461
msgid "Done."
msgstr ""

#: ../core_commands.py:247
msgid "That extension is not loaded."
msgstr ""

#: ../core_commands.py:267
msgid "Failed to reload package. Check your console or logs for details."
msgstr ""

#: ../core_commands.py:280
msgid "Shutting down... "
msgstr ""

#: ../core_commands.py:295
msgid "Restarting..."
msgstr ""

#: ../core_commands.py:332
msgid "The admin role for this guild has been set."
msgstr ""

#: ../core_commands.py:340
msgid "The mod role for this guild has been set."
msgstr ""

#: ../core_commands.py:353
msgid "Failed. Remember that you can edit my avatar up to two times a hour. The URL must be a direct link to a JPG / PNG."
msgstr ""

#: ../core_commands.py:357
msgid "JPG / PNG format only."
msgstr ""

#: ../core_commands.py:372
msgid "Game set."
msgstr ""

#: ../core_commands.py:384
msgid "Listening set."
msgstr ""

#: ../core_commands.py:396
msgid "Watching set."
msgstr ""

#: ../core_commands.py:425
msgid "Status changed to %s."
msgstr ""

#: ../core_commands.py:456
msgid "Failed to change name. Remember that you can only do it up to 2 times an hour. Use nicknames if you need frequent changes. `{}set nickname`"
msgstr ""

#: ../core_commands.py:471
msgid "I lack the permissions to change my own nickname."
msgstr ""

#: ../core_commands.py:485 ../core_commands.py:498
msgid "Prefix set."
msgstr ""

#: ../core_commands.py:494
msgid "Guild prefixes have been reset."
msgstr ""

#: ../core_commands.py:517
msgid ""
"\n"
"Verification token:"
msgstr ""

#: ../core_commands.py:520
msgid ""
"Remember:\n"
msgstr ""

#: ../core_commands.py:523
msgid "I have printed a one-time token in the console. Copy and paste it here to confirm you are the owner."
msgstr ""

#: ../core_commands.py:531
msgid "The set owner request has timed out."
msgstr ""

#: ../core_commands.py:537
msgid "You have been set as owner."
msgstr ""

#: ../core_commands.py:539
msgid "Invalid token."
msgstr ""

#: ../core_commands.py:551
msgid "Locale has been set."
msgstr ""

#: ../core_commands.py:565
msgid "Done. Sentry logging is now enabled."
msgstr ""

#: ../core_commands.py:568
msgid "Done. Sentry logging is now disabled."
msgstr ""

#: ../core_commands.py:578
msgid "User ID: %s"
msgstr ""

#: ../core_commands.py:581
msgid "through DM"
msgstr ""

#: ../core_commands.py:583
msgid "from {}"
msgstr ""

#: ../core_commands.py:584
msgid " | Server ID: %s"
msgstr ""

#: ../core_commands.py:593
msgid "Use `{}dm {} <text>` to reply to this user"
msgstr ""

#: ../core_commands.py:601
msgid "Sent by {} {}"
msgstr ""

#: ../core_commands.py:613
msgid "I cannot send your message, I'm unable to find my owner... *sigh*"
msgstr ""

#: ../core_commands.py:616
msgid "I'm unable to deliver your message. Sorry."
msgstr ""

#: ../core_commands.py:618
msgid "Your message has been sent."
msgstr ""

#: ../core_commands.py:632
msgid "Invalid ID or user not found. You can only send messages to people I share a server with."
msgstr ""

#: ../core_commands.py:638
msgid "Owner of %s"
msgstr ""

#: ../core_commands.py:642
msgid "You can reply to this message with %scontact"
msgstr ""

#: ../core_commands.py:652
msgid "Sorry, I couldn't deliver your message to %s"
msgstr ""

#: ../core_commands.py:655
msgid "Message delivered to %s"
msgstr ""

#: ../core_commands.py:675
msgid "User added to whitelist."
msgstr ""

#: ../core_commands.py:684
msgid "Whitelisted Users:"
msgstr ""

#: ../core_commands.py:704
msgid "User has been removed from whitelist."
msgstr ""

#: ../core_commands.py:706
msgid "User was not in the whitelist."
msgstr ""

#: ../core_commands.py:714
msgid "Whitelist has been cleared."
msgstr ""

#: ../core_commands.py:731
msgid "You cannot blacklist an owner!"
msgstr ""

#: ../core_commands.py:738
msgid "User added to blacklist."
msgstr ""

#: ../core_commands.py:747
msgid "blacklisted Users:"
msgstr ""

#: ../core_commands.py:767
msgid "User has been removed from blacklist."
msgstr ""

#: ../core_commands.py:769
msgid "User was not in the blacklist."
msgstr ""

#: ../core_commands.py:777
msgid "blacklist has been cleared."
msgstr ""

#: ../dev_commands.py:213
msgid "Already running a REPL session in this channel. Exit it with `quit`."
msgstr ""

#: ../dev_commands.py:218
msgid "Enter code to execute or evaluate. `exit()` or `quit` to exit."
msgstr ""

#: ../dev_commands.py:281
msgid "Unexpected error: `{}`"
msgstr ""

